package mr

import (
	"6.5840/util"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
	"unicode"
)

var filePaths []string = []string{
	"../main/pg-being_ernest.txt",
	"../main/pg-dorian_gray.txt",
	"../main/pg-frankenstein.txt",
	"../main/pg-grimm.txt",
	"../main/pg-huckleberry_finn.txt",
	"../main/pg-metamorphosis.txt",
	"../main/pg-sherlock_holmes.txt",
	"../main/pg-tom_sawyer.txt",
}

var MapF MapFunc = Map

func Map(filename string, contents string) []KeyValue {
	// function to detect word separators.
	ff := func(r rune) bool { return !unicode.IsLetter(r) }

	// split contents into an array of words.
	words := strings.FieldsFunc(contents, ff)

	kva := make([]KeyValue, 0)
	for _, w := range words {
		kv := KeyValue{w, "1"}
		kva = append(kva, kv)
	}
	return kva
}

var ReduceF ReduceFunc = Reduce

// The reduce function is called once for each key generated by the
// map tasks, with a list of all the values created for that key by
// any map task.
func Reduce(key string, values []string) string {
	// return the number of occurrences of this word.
	return strconv.Itoa(len(values))
}

func TestMakeMaster(t *testing.T) {
	t.Run("TestMakeMaster", func(t *testing.T) {
		master := MakeMaster(10, filePaths, MapF, ReduceF)
		t.Logf("%v \n", master)
		master.Lock()
		master.Unlock()
	})
}

func TestMaster_InitWorkers(t *testing.T) {
	master := MakeMaster(10, filePaths, MapF, ReduceF)
	master.Serve()
}

// TestWorkerDoTask
func TestWorkerDoTask(t *testing.T) {

	paths := make([]string, 0, len(filePaths))
	paths = append(paths, filePaths[0])
	paths = append(paths, filePaths[2:]...)
	t.Logf("master paths: %v\n", paths)
	master := MakeMaster(10, paths, MapF, ReduceF)
	filePath := filePaths[1]
	_, filename := filepath.Split(filePath)
	mapWorker := master.makeMapWorker(filePath, 1)

	err := mapWorker.start()

	if err != nil {
		t.Fatalf("worker task fail: %v.\n", err)
	}

	exist := false
	master.MapFile.ForEach(func(value util.T) bool {
		mapFilePath, ok := value.(string)
		if ok && filePath == mapFilePath {
			exist = true
			return false
		}
		return true
	})
	if exist {
		t.Fatalf("delete filename map set fail")
	}

	intermediaFilename := basePath + fmt.Sprintf("map_out_%s", filename)
	t.Logf("map intermiedia filename: %s. \n", intermediaFilename)

	exist = false
	master.ReduceTempFile.ForEach(func(value util.T) bool {
		reduceFilePath, ok := value.(string)
		if ok && intermediaFilename == reduceFilePath {
			exist = true
			return false
		}
		return true
	})
	if !exist {
		t.Fatalf("put filename reduce set fail")
	}

	reduceWorker := master.makeReduceWorker(1)

	err = reduceWorker.start()

	if err != nil {
		t.Fatalf("do task fail.")
	}

	if reduceWorker.Status&completed == 0 {
		t.Fatalf("reduce worker status fail: %v\n", reduceWorker.Status)
	}

	master.ReduceTempFile.ForEach(func(value util.T) bool {
		reduceFilePath, ok := value.(string)
		if ok && intermediaFilename == reduceFilePath {
			t.Fatalf("reduce worker delete map fail: %s\n", intermediaFilename)
			return false
		}
		return true
	})
}

func TestReadFile(t *testing.T) {
	filepath := filePaths[0]
	filename, _ := strings.CutPrefix(filepath, "../main/")
	content := readFile(filepath)

	intermediaFilename := transferIntermediaFile(filename, Map(filename, content))

	intermediaFilePath := basePath + intermediaFilename
	bContent, _ := os.ReadFile(intermediaFilePath)
	m := parseIntermediaFile(string(bContent))

	t.Logf("intermedia file result:\n")
	var result string
	for k, v := range m {
		result = Reduce(k, v)
		t.Logf("%s-%s\n", k, result)
	}

	t.Logf("reduce finished. removing intermedia file...\n")
	_ = os.Remove(basePath + intermediaFilename)
}

func TestGoroutineForTwo(t *testing.T) {
	m := MakeMaster(10, filePaths, Map, Reduce)
	m.Serve()
}

func TestMapFileWrite(t *testing.T) {
	fileContent := readFile(filePaths[0])

	kvs := MapF(filePaths[0], fileContent)

	buf := make([]byte, 0, 64*1024)
	cnt := 0
	for _, kv := range kvs {
		input := fmt.Sprintf("%s %s\n", kv.Key, kv.Value)
		cnt += len(input)

		if cap(buf) <= len(buf)+len(input) {
			canWrite := cap(buf) - len(buf)
			buf = append(buf, input[:canWrite]...)
			input = input[canWrite:]
			if len(buf) == 64*1024 {
				t.Logf("缓冲区充满了, 正在写入 %d 字节, 剩下 %d 字节待缓冲\n", len(buf), len(input))
				buf = buf[:0]
			} else {
				t.Fatalf("缓冲区没有充满, len = %d\n", len(buf))
			}

		}
		t.Logf("缓冲 %d 字节数据\n", len(input))
		buf = append(buf, input...)
	}
	if len(buf) > 0 {
		// do sth
		t.Logf("最后剩下 %d 字节数据\n", len(buf))
		if cnt%(64*1024) != len(buf) {
			t.Fatalf("漏传了 %d 个字节\n", cnt%(64*1026)-len(buf))
		}
		buf = buf[:0]
	}

}
