package mr

import (
	"fmt"
	"os"
	"strconv"
	"strings"
	"testing"
	"unicode"
)

var filePath []string = []string{
	"../main/pg-being_ernest.txt",
	"../main/pg-dorian_gray.txt",
	"../main/pg-frankenstein.txt",
	"../main/pg-grimm.txt",
	"../main/pg-huckleberry_finn.txt",
	"../main/pg-metamorphosis.txt",
	"../main/pg-sherlock_holmes.txt",
	"../main/pg-tom_sawyer.txt",
}

var MapF MapFunc = Map

func Map(filename string, contents string) []KeyValue {
	// function to detect word separators.
	ff := func(r rune) bool { return !unicode.IsLetter(r) }

	// split contents into an array of words.
	words := strings.FieldsFunc(contents, ff)

	kva := make([]KeyValue, 0)
	for _, w := range words {
		kv := KeyValue{w, "1"}
		kva = append(kva, kv)
	}
	return kva
}

var ReduceF ReduceFunc = Reduce

// The reduce function is called once for each key generated by the
// map tasks, with a list of all the values created for that key by
// any map task.
func Reduce(key string, values []string) string {
	// return the number of occurrences of this word.
	return strconv.Itoa(len(values))
}

func TestMakeMaster(t *testing.T) {
	t.Run("TestMakeMaster", func(t *testing.T) {
		master := MakeMaster(10, filePath, MapF, ReduceF)
		t.Logf("%v \n", master)
	})
}

func TestMaster_InitWorkers(t *testing.T) {
	master := MakeMaster(10, filePath, MapF, ReduceF)
	master.InitWorkers()
}

func TestWorkerDoTask(t *testing.T) {
	master := MakeMaster(10, filePath, MapF, ReduceF)
	filename := filePath[0]
	mapWorker := master.MakeMapWorker(filename)

	err := mapWorker.doTask()

	if err != nil {
		t.Fatalf("do task fail.")
	}

	_, exist := master.MapFileMap[filename]
	if exist {
		t.Fatalf("delete filename map set fail")
	}

	intermediaFilename := fmt.Sprintf("map_out_%s", filename)
	t.Logf("map intermiedia filename: %s. \n", intermediaFilename)

	reduceTempFile, exist := master.ReduceTempFileMap[intermediaFilename]
	if !exist {
		t.Fatalf("put filename reduce set fail")
	}

	reduceWorker := master.MakeReduceWorker()

	err = reduceWorker.doTask()

	if err != nil {
		t.Fatalf("do task fail.")
	}

	if reduceTempFile {
		keyValues := parseIntermediaFile(readFile(intermediaFilename))
		for k, v := range keyValues {
			reduceWorker.ReduceF(k, v)
		}
	}
}

func TestReadFile(t *testing.T) {
	filepath := filePath[0]
	filename, _ := strings.CutPrefix(filepath, "../main/")
	content := readFile(filepath)

	intermediaFilename := transferIntermediaFile(filename, Map(filename, content))

	intermediaFilePath := basePath + intermediaFilename
	bContent, _ := os.ReadFile(intermediaFilePath)
	m := parseIntermediaFile(string(bContent))

	t.Logf("intermedia file result:\n")
	var result string
	for k, v := range m {
		result = Reduce(k, v)
		t.Logf("%s-%s\n", k, result)
	}

	t.Logf("reduce finished. removing intermedia file...\n")
	_ = os.Remove(basePath + intermediaFilename)
}
